### ISSUE TITLE
meQuery only execute once

### ISSUE THREAD

**Issue by sgalcheung** [Xetera/xetera.dev#73]
https://github.com/Xetera/xetera.dev/blob/6521238915fee28505b4fe600b700d45bc8fc46e/src/scripts/me.ts#L41

The meQuery is a constant variable, and it will only execute once.

The build result code of meQuery is below:
```
const meQuery = executeOperation(GRAPHQL_URL, query, {
  filter: "PURCHASED"
}).then((r) => {
  if (r.errors) {
    console.log(inspect(r.errors, { depth: Infinity, colors: true }));
    throw new Error("Failed to execute GraphQL query");
  }
  return r.data;
});
```

**Comment by Xetera** [comment]
I can see why that would be annoying in development when you're experimenting but that's kind of the intended behavior. The same query doesn't have to be run multiple times in this context.

If you're also using your own `xetera/me` you can go to `/graphiql` (https://me.xetera.dev/graphiql) to play around with the graphql response, otherwise restarting the process seems reasonable to me since you only mess around with it once and leave it alone for the most part

**Comment by sgalcheung** [comment]
If the background has some new PURCHASED books, it will always get the same query result, because it executes once.
Do you mean your website wants to display the first query result?

Even if a new result is returned, it will filter the results of the first ten books. Therefore, do you think it would be appropriate to do this here?

**Comment by Xetera** [comment]
Yes the entire page is built statically. I rebuild the site every day to pick up on updates to that query result, but otherwise there's no backend that can run that query more than once to begin with

**Comment by sgalcheung** [comment]
All right, I noticed your blog output mode is static.
